export const cartCols =[ "products", "name of product", "price", "quantity","remove","total"]
export const navOpts = [
    [{
    name: "all",
    link: "/products/all"
    },{
    name: "pottery",
    link: "/products/pottery"
    },{
    name: "knives",
    link: "/products/knives"
    },{
    name: "paintings",
    link: "/products/paintings"
    },{
    name: "wood-work",
    link: "/products/wood-work"
    }],
    [{
    name: "Da-Vito-Degal",
    link: "/artisans/Da-Vito-Degal"
    },{
    name: "Lucy-Moon",
    link: "/artisans/Lucy-Moon"
    },{
    name: "Vince-Van-Dro",
    link: "/artisans/Vince-Van-Dro"
    },{
    name: "Ikel-Bangelo",
    link: "/artisans/Ikel-Bangelo"
    }],
    [{
    name: "log-in",
    link: "/log-in"
    },{
    name: "sign-up",
    link: "/sign-up"
    }]
]

export const navOptsLoggedIn = [
    [{
    name: "all",
    link: "/products/all"
    },{
    name: "pottery",
    link: "/products/pottery"
    },{
    name: "knives",
    link: "/products/knives"
    },{
    name: "paintings",
    link: "/products/paintings"
    },{
    name: "wood-work",
    link: "/products/wood-work"
    }],
    [{
    name: "Da-Vito-Degal",
    link: "/artisans/Da-Vito-Degal"
    },{
    name: "Lucy-Moon",
    link: "/artisans/Lucy-Moon"
    },{
    name: "Vince-Van-Dro",
    link: "/artisans/Vince-Van-Dro"
    },{
    name: "Ikel-Bangelo",
    link: "/artisans/Ikel-Bangelo"
    }],
    [{
    name: "log-out",
    link: "/log-out"
    },{
    name : "my-cart",
    link: "/my-cart"
    }]
]

export const navHeadings = ["Products","Artisans","Account"];

export const slides = [
    {img:"https://ffcp.s3.amazonaws.com/tfc/Resorts/palazzo/explore/arts_crafts/terrocotta_artisan/sizes/PM_artisans-9928.jpg",
    caption: "Welcome to Art Mart"},
    {img:"https://www.primeis.com/wp-content/uploads/2017/07/carpenter.jpg",
    caption: "A market and community of craftsmen, craftswomen, and seekers of unique hand-made crafts."}
]


export const columns = [
    [{
        name : "The goal behind the Art Mart is to provide an audience to those who like building things with their hands all while presenting them with the opportunity to tell each item's story.",
        isLink: false
    }],
    [{
        name: "pottery",
        isLink: true,
        link: "/products/pottery"
    },{
        name: "knives",
        isLink: true,
        link: "/products/knives"
    },{
        name: "paintings",
        isLink: true,
        link: "/products/paintings"
    },{
        name: "wood-work",
        isLink: true,
        link: "/products/wood-work"
    }],
    [{
        name: "about-us",
        isLink: true,
        link: "/about-us"
    },{
        name: "terms",
        isLink: true,
        link: "/terms"
    },{
        name: "shipping-rates",
        isLink: true,
        link: "/shipping-rates"
    }],
    [{
        name: "Atlanta, GA 30305",
        isLink: false
    },{
        name: "artmart@gmail.com",
        isLink: false
    }],[{
        name: "2019 Copyright: Art Mart",
        isLink: false
    }]
]

export const headings = ["Art Mart","Products","General","Contact"];

export const storeProducts = [
    { 
        product_id : 'knives1',
        product_type: 'knives',
        title : 'beautiful utility knife',
        img : '/img/knives1.jpg',
        price : 12,
        artist : 'Da Vito Degal',
        info : 'easy to conceal and carry lightweight blade for many uses with beautiful design.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'knives2',
        product_type: 'knives',
        title : 'woodworking steel blade',
        img : '/img/knives2.jpg',
        price : 29,
        artist : 'Vince Van Dro',
        info : 'custom handle makes sharp angles and precise cuts easy and enjoyable.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'knives3',
        product_type: 'knives',
        title : 'small camping blade',
        img : '/img/knives3.jpg',
        price : 8,
        artist : 'Ikel Bangelo',
        info : 'great blade for camping and/or woodworking. Great first blade.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'knives4',
        product_type: 'knives',
        title : 'damascus steel machete',
        img : '/img/knives4.jpg',
        price : 30,
        artist : 'Lucy Moon',
        info : 'large sharp machete made of damascus steel great for cutting into small trees and branches.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'knives5',
        product_type: 'knives',
        title : 'steel short knives',
        img : '/img/knives5.jpg',
        price : 12,
        artist : 'Vince Van Dro',
        info : 'great for food, camping and comes with its own handmade leather case.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'knives6',
        product_type: 'knives',
        title : 'large hunting knife',
        img : '/img/knives6.jpg',
        price : 42,
        artist : 'Da Vito Degal',
        info : 'heavy-duty damascus steel blade great for hunting as well as cutting into small trees and/or branches.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'knives7',
        product_type: 'knives',
        title : 'axe blade',
        img : '/img/knives7.jpg',
        price : 22,
        artist : 'Ikel Bangelo',
        info : 'heavy blade great for splitting wood.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'knives8',
        product_type: 'knives',
        title : 'unique blade comes with sleeve',
        img : '/img/knives8.jpg',
        price : 16,
        artist : 'Lucy Moon',
        info : 'sharp edge blade with unique handle.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'knives9',
        product_type: 'knives',
        title : 'throwing blade',
        img : '/img/knives9.jpg',
        price : 13,
        artist : 'Vince Van Dro',
        info : 'beautiful blade perfect weight for knife throwing.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'knives10',
        product_type: 'knives',
        title : 'machete',
        img : '/img/knives10.jpg',
        price : 17,
        artist : 'Da Vito Degal',
        info : 'great general purpose machete.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'knives11',
        product_type: 'knives',
        title : 'small cooking axe',
        img : '/img/knives11.jpg',
        price : 24,
        artist : 'Ikel Bangelo',
        info : 'great for meat-chopping and dicing up other indgredients in large quanitities.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'knives12',
        product_type: 'knives',
        title : 'old handmade throwing blade',
        img : '/img/knives12.jpg',
        price : 20,
        artist : 'Lucy Moon',
        info : 'small throwing blade with wood-dye handle.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'pottery1',
        product_type: 'pottery',
        title : 'accesorizable vase',
        img : '/img/pottery1.jpg',
        price : 30,
        artist : 'Lucy Moon',
        info : 'collect amulets and hook them to this beautiful vase (two included).',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'pottery2',
        product_type: 'pottery',
        title : 'floral mug',
        img : '/img/pottery2.jpg',
        price : 5,
        artist : 'Ikel Bangelo',
        info : 'start your day with a cup of joe in this painted floral mug.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'pottery3',
        product_type: 'pottery',
        title : 'hearts mug',
        img : '/img/pottery3.jpg',
        price : 8,
        artist : 'Da Vito Degal',
        info : 'makes for a great valentines day gift.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'pottery4',
        product_type: 'pottery',
        title : 'colorful bowl',
        img : '/img/pottery4.jpg',
        price : 14,
        artist : 'Vince Van Dro',
        info : 'impress company and serve your next snacks in this colorful bowl.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'pottery5',
        product_type: 'pottery',
        title : 'night owl mug',
        img : '/img/pottery5.jpg',
        price : 13,
        artist : 'Lucy Moon',
        info : 'next time you need a cup of joe to burn the midnight oil consider this mug you old night owl you.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'pottery6',
        product_type: 'pottery',
        title : 'family tree mug',
        img : '/img/pottery6.jpg',
        price : 11,
        artist : 'Ikel Bangelo',
        info : 'apple tree design mug.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'pottery7',
        product_type: 'pottery',
        title : 'hand-painted mug',
        img : '/img/pottery7.jpg',
        price : 5,
        artist : 'Da Vito Degal',
        info : 'basic mug great gift for relatives or friends you dont really like that much.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'pottery8',
        product_type: 'pottery',
        title : 'doggie bone bowl',
        img : '/img/pottery8.jpg',
        price : 15,
        artist : 'Vince Van Dro',
        info : 'a beautiful bowl just for your best friend.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'pottery9',
        product_type: 'pottery',
        title : 'the meow mug',
        img : '/img/pottery9.jpg',
        price :14,
        artist : 'Lucy Moon',
        info : 'let your inner cat person out with the meow mug.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'pottery10',
        product_type: 'pottery',
        title : 'rainbow kitty bowl',
        img : '/img/pottery10.jpg',
        price : 9,
        artist : 'Ikel Bangelo',
        info : 'hand-made bowl for your kitten.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'pottery11',
        product_type: 'pottery',
        title : 'handmade mug with coaster',
        img : '/img/pottery11.jpg',
        price : 6,
        artist : 'Da Vito Degal',
        info : 'arts and crafts classic - coaster included.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'pottery12',
        product_type: 'pottery',
        title : 'turtle love',
        img : '/img/pottery12.jpg',
        price : 10,
        artist : 'Vince Van Dro',
        info : 'love turtles ? great! now buy this mug.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'paintings1',
        product_type: 'paintings',
        title : 'Spring Bloom',
        img : '/img/paintings1.jpg',
        price : 500,
        artist : 'Lucy Moon',
        info : 'Lucy moon captures the esscence of the spring bloom with contrasting colors.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'paintings2',
        product_type: 'paintings',
        title : 'Weary',
        img : '/img/paintings2.jpg',
        price : 600,
        artist : 'Lucy Moon',
        info : 'Weary vividly depicts the exhaustion of a women as she lays her head down for a quick rest.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'paintings3',
        product_type: 'paintings',
        title : 'Spring Growth',
        img : '/img/paintings3.jpg',
        price : 700,
        artist : "Lucy Moon",
        info : "In part two of the Spring seres, Lucy moon depicts the growth of seeds in spring.",
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'paintings4',
        product_type: 'paintings',
        title : 'Lone Wolf',
        img : '/img/paintings4.jpg',
        price : 200,
        artist : 'Vince Van Dro',
        info : 'Magestic wolf perches on top of a cliff during a full moon.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'paintings5',
        product_type: 'paintings',
        title : 'Best Friends',
        img : '/img/paintings5.jpg',
        price : 450,
        artist : 'Vince Van Dro',
        info : 'Man with his best friends as he rides long the canals of the Bayou.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'paintings6',
        product_type: 'paintings',
        title : 'New Born',
        img : '/img/paintings6.jpg',
        price : 780,
        artist : 'Vince Van Dro',
        info : 'Siberian Tiger cuddles her cub as the sun warms thier fur.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'paintings7',
        product_type: 'paintings',
        title : 'Curious Puppy',
        img : '/img/paintings7.jpg',
        price : 1000,
        artist : 'Da Vito Degal',
        info : 'Colorful cute puppy letting his inner geek fly.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'paintings8',
        product_type: 'paintings',
        title : 'Blissfull kiss',
        img : '/img/paintings8.jpg',
        price : 800,
        artist : 'Da Vito Degal',
        info : 'Da Vito captures the feelings of bliss with vivid colors.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'paintings9',
        product_type: 'paintings',
        title : 'Human Mermaid',
        img : '/img/paintings9.jpg',
        price : 754,
        artist : 'Da Vito Degal',
        info : 'Da Vito depits the humanistic characteristics traits of a mystical mermaid as she makes landfall.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'paintings10',
        product_type: 'paintings',
        title : 'Magestic Elephant',
        img : '/img/paintings10.jpg',
        price : 321,
        artist : 'Ikel Bangelo',
        info : 'An elephant approaching can be both magestic and terrifying.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'paintings11',
        product_type: 'paintings',
        title : 'As She Walks Away',
        img : '/img/paintings11.jpg',
        price : 510,
        artist : 'Ikel Bangelo',
        info : 'Vidi melting colors depicts the absence of a women.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'paintings12',
        product_type: 'paintings',
        title : 'Mustangs',
        img : '/img/paintings12.jpg',
        price : 1500,
        artist : 'Ikel Bangelo',
        info : 'Wild horces look for new areas to roam free.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'wood-work1',
        product_type: 'wood-work',
        title : 'The Holder',
        img : '/img/wood-work1.jpg',
        price : 43,
        artist : 'Vince Van Dro',
        info : 'Multi use nature holder that can hold things such as bird seeds or plants.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'wood-work2',
        product_type: 'wood-work',
        title : 'Jewelry Box',
        img : '/img/wood-work2.jpg',
        price : 108,
        artist : 'Vince Van Dro',
        info : 'Hand carved perfection of artistry to hold all your valuable things.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'wood-work3',
        product_type: 'wood-work',
        title : 'Bird Mansion',
        img : '/img/wood-work3.jpg',
        price : 56,
        artist : 'Vince Van Dro',
        info : 'Multiple room bird house for birds with big families.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'wood-work4',
        product_type: 'wood-work',
        title : 'Wine Rack',
        img : '/img/wood-work4.jpg',
        price : 76,
        artist : 'Da Vito Degal',
        info : 'A wine rack that holds all your wino needs.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'wood-work5',
        product_type: 'wood-work',
        title : 'Cutting Board',
        img : '/img/wood-work5.jpg',
        price : 90,
        artist : 'Da Vito Degal',
        info : 'Made from exquisite imported pine, this cutting board flavors your food with exotic pine tastes.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'wood-work6',
        product_type: 'wood-work',
        title : 'WoodCarving essential notebook',
        img : '/img/wood-work6.jpg',
        price : 12,
        artist : 'Da Vito Degal',
        info : 'All woodworkers need to write down notes for thier projects. The woodcarving notebook povides all your woodworking notetaking needs.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'wood-work7',
        product_type: 'wood-work',
        title : 'Patriot',
        img : '/img/wood-work7.jpg',
        price : 1050,
        artist : 'Ikel Bangelo',
        info : 'American Flag made from American Oak to fit your patriotic needs.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'wood-work8',
        product_type: 'wood-work',
        title : 'Medievil Bed Box',
        img : '/img/wood-work8.jpg',
        price : 2000,
        artist : 'Ikel Bangelo',
        info : ' Made from Canadian maple, this stylish bed box will emit smells that will put you to a fast slumber. ',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'wood-work9',
        product_type: 'wood-work',
        title : 'TV Cabinet',
        img : '/img/wood-work9.jpg',
        price : 700,
        artist : 'Ikel Bangelo',
        info : 'This special tv cabinet is made from a walnut tree that will impress movie nights.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'wood-work10',
        product_type: 'wood-work',
        title : 'The Rocking Chair',
        img : '/img/wood-work10.jpg',
        price : 2031,
        artist : 'Lucy Moon',
        info : 'This rocking chair made from mahogany will rock your world.',
        inCart : false,
        count : 0,
        total : 0,      
        id: null,
    },{ 
        product_id : 'wood-work11',
        product_type: 'wood-work',
        title : 'All natural bed frame',
        img : '/img/wood-work11.jpg',
        price : 1280,
        artist : 'Lucy Moon',
        info : 'This nature friendly bed frame made from birch and beech wood makes you feel like you are sleeping in the deep wilderness.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
    },{ 
        product_id : 'wood-work12',
        product_type: 'wood-work',
        title : 'The Cabinet',
        img : '/img/wood-work12.jpg',
        price : 804,
        artist : 'Lucy Moon',
        info : 'This cabinet made from American cedar will store all your essential needs.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
}]

export const detailProduct = {
        product_id : 'wood-work12',
        product_type: 'wood-work',
        title : 'The Cabinet',
        img : '/img/wood-work12.jpg',
        price : 804,
        artist : 'Lucy Moon',
        info : 'This cabinet made from American cedar will store all your essential needs.',
        inCart : false,
        count : 0,
        total : 0,
        id: null,
}