export const navOpts = [
    [{
    name: "all-products"
    },{
    name: "pottery",
    },{
    name: "knives/swords",
    },{
    name: "paintings",
    },{
    name: "wood-work",
    }],
    [{
    name: "log-in",
    },{
    name: "sign-up",
    },{
    name: "log-out",
    },{
    name: "settings",
    },{
    name : "my-cart",
    }]
]

export const navHeadings = ["Products","Account"];

export const slides = [
    {img:"https://ffcp.s3.amazonaws.com/tfc/Resorts/palazzo/explore/arts_crafts/terrocotta_artisan/sizes/PM_artisans-9928.jpg",
    caption: "Welcome to Art Mart"},
    {img:"https://www.primeis.com/wp-content/uploads/2017/07/carpenter.jpg",
    caption: "A market and community of craftsmen, craftswomen, and seekers of unique hand-made crafts."}
]

export const signUpData = [
    [{
        label:'Username',
        type: 'text',
    },
    {
        label:'Email',
        type: 'email',
    }],
    [{
        label:'Password',
        type: 'password',
    },{
        label: 'Confirm Password',
        type: 'password'
    }],
    [{
        label:'Address',
        type: 'text',
    }],
    [{
        label:'City',
        type: 'text',
    },{
        label: 'State',
        type: 'select'
    },
    {
        label:'Zip',
        type: 'number',
    }],
    [{
        label:'Profile Picture',
        type: 'file',
    }],
    [{
        label: 'I have read and agree to follow the terms',
        type: 'checkbox',
    }]
]

export const logInData = [
    {
        label:'Username',
        type: 'text'
    },
    {
        label:'Email',
        type: 'email'
    },
    {
        label:'Password',
        type: 'password'
    }
]

export const columns = [
    [{
        name : "The goal behind the Art Mart is to provide an audience to those who like building things with their\
        hands all while presenting them with the opportunity to tell each item's story.",
        isLink: false
    }],
    [{
        name: "pottery",
        isLink: true
    },{
        name: "knives/swords",
        isLink: true
    },{
        name: "paintings",
        isLink: true
    },{
        name: "wood-work",
        isLink: true
    }],
    [{
        name: "about-us",
        isLink: true
    },{
        name: "terms",
        isLink: true
    },{
        name: "shipping-rates",
        isLink: true
    },{
        name: "help",
        isLink: true
    }],
    [{
        name: "Atlanta, GA 30305",
        isLink: false
    },{
        name: "artmart@gmail.com",
        isLink: false
    }],[{
        name: "2019 Copyright: Art Mart",
        isLink: false
    }]
]

export const headings = ["Art Mart","Products","Account","Contact"];

export const storeProducts = [
  { 
product_id : 'knife1',
product_type: 'knife',
title : '',
img : 'img/knife1.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'knife2',
product_type: 'knife',
title : '',
img : 'img/knife2.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'knife3',
product_type: 'knife',
title : '',
img : 'img/knife3.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'knife4',
product_type: 'knife',
title : '',
img : 'img/knife4.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'knife5',
product_type: 'knife',
title : '',
img : 'img/knife5.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'knife6',
product_type: 'knife',
title : '',
img : 'img/knife6.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'knife7',
product_type: 'knife',
title : '',
img : 'img/knife7.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'knife8',
product_type: 'knife',
title : '',
img : 'img/knife8.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'knife9',
product_type: 'knife',
title : '',
img : 'img/knife9.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'knife10',
product_type: 'knife',
title : '',
img : 'img/knife10.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'knife11',
product_type: 'knife',
title : '',
img : 'img/knife11.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'knife12',
product_type: 'knife',
title : '',
img : 'img/knife12.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'pottery1',
product_type: 'pottery',
title : '',
img : 'img/pottery1.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'pottery2',
product_type: 'pottery',
title : '',
img : 'img/pottery2.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'pottery3',
product_type: 'pottery',
title : '',
img : 'img/pottery3.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'pottery4',
product_type: 'pottery',
title : '',
img : 'img/pottery4.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'pottery5',
product_type: 'pottery',
title : '',
img : 'img/pottery5.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'pottery6',
product_type: 'pottery',
title : '',
img : 'img/pottery6.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'pottery7',
product_type: 'pottery',
title : '',
img : 'img/pottery7.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'pottery8',
product_type: 'pottery',
title : '',
img : 'img/pottery8.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'pottery9',
product_type: 'pottery',
title : '',
img : 'img/pottery9.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'pottery10',
product_type: 'pottery',
title : '',
img : 'img/pottery10.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'pottery11',
product_type: 'pottery',
title : '',
img : 'img/pottery11.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'pottery12',
product_type: 'pottery',
title : '',
img : 'img/pottery12.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'painting1',
product_type: 'painting',
title : 'Spring Bloom',
img : 'img/painting1.jpg',
price : 500,
artist : 'Lucy Moon',
info : 'Lucy moon captures the esscence of the spring bloom with contrasting colors. ',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'painting2',
product_type: 'painting',
title : 'Weary',
img : 'img/painting2.jpg',
price : 600,
artist : 'Lucy Moon',
info : 'Weary vividly depicts the exhaustion of a women as she lays her head down for a quick rest. ',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'painting3',
product_type: 'painting',
title : 'Spring Growth',
img : 'img/painting3.jpg',
price : 700,
artist : "Lucy Moon",
info : "In part two of the Spring seres, Lucy moon depicts the growth of seeds in spring.",
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'painting4',
product_type: 'painting',
title : 'Lone Wolf',
img : 'img/painting4.jpg',
price : 200,
artist : 'Vince Van Dro',
info : 'Magestic wolf perches on top of a cliff during a full moon.',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'painting5',
product_type: 'painting',
title : 'Best Friends',
img : 'img/painting5.jpg',
price : 450,
artist : 'Vince Van Dro',
info : 'Man with his best friends as he rides long the canals of the Bayou.',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'painting6',
product_type: 'painting',
title : 'New Born',
img : 'img/painting6.jpg',
price : '',
artist : 'Vince Van Dro',
info : 'Siberian Tiger cuddles her cub as the sun warms thier fur.',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'painting7',
product_type: 'painting',
title : 'Curious Puppy',
img : 'img/painting7.jpg',
price : 1000,
artist : 'Da Vito Degal',
info : 'Colorful cute puppy letting his inner geek fly.',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'painting8',
product_type: 'painting',
title : 'Blissfull kiss',
img : 'img/painting8.jpg',
price : 800,
artist : 'Da Vito Degal',
info : 'Da Vito captures the feelings of bliss with vivid colors.',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'painting9',
product_type: 'painting',
title : 'Human Mermaid',
img : 'img/painting9.jpg',
price : 754,
artist : 'Da Vito Degal',
info : 'Da Vito depits the humanistic characteristics traits of a mystical mermaid as she makes landfall.',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'painting10',
product_type: 'painting',
title : 'Magestic Elephant',
img : 'img/painting10.jpg',
price : 321,
artist : 'Ikel Bangelo',
info : 'An elephant approaching can be both magestic and terrifying.',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'painting11',
product_type: 'painting',
title : 'As She Walks Away',
img : 'img/painting11.jpg',
price : 510,
artist : 'Ikel Bangelo',
info : 'Vidi melting colors depicts the absence of a women.',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'painting12',
product_type: 'painting',
title : 'Mustangs',
img : 'img/painting12.jpg',
price : 1500,
artist : 'Ikel Bangelo',
info : 'Wild horces look for new areas to roam free.',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'ww1',
product_type: 'ww',
title : 'The Holder',
img : 'img/ww1.jpg',
price : 43,
artist : 'Vince Van Dro',
info : 'Multi use nature holder that can hold things such as bird seeds or plants.',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'ww2',
product_type: 'ww',
title : 'Jewelry Box',
img : 'img/ww2.jpg',
price : 108,
artist : 'Vince Van Dro',
info : 'Hand carved perfection of artistry to hold all your valuable things.',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'ww3',
product_type: 'ww',
title : 'Bird Mansion',
img : 'img/ww3.jpg',
price : 56,
artist : 'Vince Van Dro',
info : 'Multiple room bird house for birds with big families.',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'ww4',
product_type: 'ww',
title : 'Wine Rack',
img : 'img/ww4.jpg',
price : 76,
artist : 'Da Vito Degal',
info : 'A wine rack that holds all your wino needs.',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'ww5',
product_type: 'ww',
title : 'Cutting Board',
img : 'img/ww5.jpg',
price : 90,
artist : 'Da Vito Degal',
info : 'Made from exquisite imported pine, this cutting board flavors your food with exotic pine tastes.',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'ww6',
product_type: 'ww',
title : 'WoodCarving essential notebook',
img : 'img/ww6.jpg',
price : 12,
artist : 'Da Vito Degal',
info : 'All woodworkers need to write down notes for thier projects. The woodcarving notebook povides all your woodworking notetaking needs.',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'ww7',
product_type: 'ww',
title : 'Patriot',
img : 'img/ww7.jpg',
price : 1050,
artist : 'Ikel Bangelo',
info : 'American Flag made from American Oak to fit your patriotic needs.',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'ww8',
product_type: 'ww',
title : 'Medievil Bed Box',
img : 'img/ww8.jpg',
price : 2000,
artist : 'Ikel Bangelo',
info : ' Made from Canadian maple, this stylish bed box will emit smells that will put you to a fast slumber. ',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'ww9',
product_type: 'ww',
title : 'TV Cabinet',
img : 'img/ww9.jpg',
price : 700,
artist : 'Ikel Bangelo',
info : 'This special tv cabinet is made from a walnut tree that will impress movie nights.',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'ww10',
product_type: 'ww',
title : 'The Rocking Chair',
img : 'img/ww10.jpg',
price : 2031,
artist : 'Lucy Moon',
info : 'This rocking chair made from Mahogany will rock your world.',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'ww11',
product_type: 'ww',
title : 'All natural bed frame',
img : 'img/ww11.jpg',
price : 1280,
artist : 'Lucy Moon',
info : 'This nature friendly bed frame made from birch and beech wood makes you feel like you are sleeping in the deep wilderness.',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'ww12',
product_type: 'ww',
title : 'The Cabinet',
img : 'img/ww12.jpg',
price : 804,
artist : 'Lucy Moon',
info : 'This cabinet made from american Cedar will store all your essential needs.',
inCart : false,
count : 0,
total : 0,
id: null,
}]
