export const navOpts = [
    [{
    name: "all-products"
    },{
    name: "pottery",
    },{
    name: "knives/swords",
    },{
    name: "paintings",
    },{
    name: "wood-work",
    }],
    [{
    name: "log-in",
    },{
    name: "sign-up",
    },{
    name: "log-out",
    },{
    name: "settings",
    },{
    name : "my-cart",
    }]
]

export const navHeadings = ["Products","Account"];

export const slides = [
    {img:"https://ffcp.s3.amazonaws.com/tfc/Resorts/palazzo/explore/arts_crafts/terrocotta_artisan/sizes/PM_artisans-9928.jpg",
    caption: "Welcome to Art Mart"},
    {img:"https://www.primeis.com/wp-content/uploads/2017/07/carpenter.jpg",
    caption: "A market and community of craftsmen, craftswomen, and seekers of unique hand-made crafts."}
]

export const signUpData = [
    [{
        label:'Username',
        type: 'text',
    },
    {
        label:'Email',
        type: 'email',
    }],
    [{
        label:'Password',
        type: 'password',
    },{
        label: 'Confirm Password',
        type: 'password'
    }],
    [{
        label:'Address',
        type: 'text',
    }],
    [{
        label:'City',
        type: 'text',
    },{
        label: 'State',
        type: 'select'
    },
    {
        label:'Zip',
        type: 'number',
    }],
    [{
        label:'Profile Picture',
        type: 'file',
    }],
    [{
        label: 'I have read and agree to follow the terms',
        type: 'checkbox',
    }]
]

export const logInData = [
    {
        label:'Username',
        type: 'text'
    },
    {
        label:'Email',
        type: 'email'
    },
    {
        label:'Password',
        type: 'password'
    }
]

export const columns = [
    [{
        name : "The goal behind the Art Mart is to provide an audience to those who like building things with their\
        hands all while presenting them with the opportunity to tell each item's story.",
        isLink: false
    }],
    [{
        name: "pottery",
        isLink: true
    },{
        name: "knives/swords",
        isLink: true
    },{
        name: "paintings",
        isLink: true
    },{
        name: "wood-work",
        isLink: true
    }],
    [{
        name: "about-us",
        isLink: true
    },{
        name: "terms",
        isLink: true
    },{
        name: "shipping-rates",
        isLink: true
    },{
        name: "help",
        isLink: true
    }],
    [{
        name: "Atlanta, GA 30305",
        isLink: false
    },{
        name: "artmart@gmail.com",
        isLink: false
    }],[{
        name: "2019 Copyright: Art Mart",
        isLink: false
    }]
]

export const headings = ["Art Mart","Products","Account","Contact"];

export const storeProducts = [
  { 
product_id : 'knife1',
product_type: 'knife',
title : 'beautiful utility knife',
img : 'img/knife1.jpg',
price : 12,
artist : 'Da Vito Degal',
info : 'easy to conceal and carry lightweight blade for many uses with beautiful design.',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'knife2',
product_type: 'knife',
title : 'woodworking steel blade',
img : 'img/knife2.jpg',
price : 29,
artist : 'vince van dro',
info : 'custom handle makes sharp angles and precise cuts easy and enjoyable.',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'knife3',
product_type: 'knife',
title : 'small camping blade',
img : 'img/knife3.jpg',
price : 8,
artist : 'ikel bangelo',
info : 'great blade for camping and/or woodworking. Great first blade.',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'knife4',
product_type: 'knife',
title : 'damascus steel machete',
img : 'img/knife4.jpg',
price : 30,
artist : 'lucy moon',
info : 'large sharp machete made of damascus steel great for cutting into small trees and branches. ',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'knife5',
product_type: 'knife',
title : 'steel short knife',
img : 'img/knife5.jpg',
price : 12,
artist : 'vince van dro',
info : 'great for food, camping and comes with its own handmade leather case.',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'knife6',
product_type: 'knife',
title : 'large hunting knife',
img : 'img/knife6.jpg',
price : 42,
artist : 'da vito degal',
info : 'heavy-duty damascus steel blade great for hunting as well as cutting into small trees and/or branches.',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'knife7',
product_type: 'knife',
title : 'axe blade',
img : 'img/knife7.jpg',
price : 22,
artist : 'ikel bangelo',
info : 'heavy blade great for splitting wood.',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'knife8',
product_type: 'knife',
title : 'unique blade comes with sleeve',
img : 'img/knife8.jpg',
price : 16,
artist : 'lucy moon',
info : 'sharp edge blade with unique handle',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'knife9',
product_type: 'knife',
title : 'throwing blade',
img : 'img/knife9.jpg',
price : 13,
artist : 'vince van dro',
info : 'beautiful blade perfect weight for knife throwing',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'knife10',
product_type: 'knife',
title : 'machete',
img : 'img/knife10.jpg',
price : 17,
artist : 'da vito degal',
info : 'great general purpose machete.',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'knife11',
product_type: 'knife',
title : 'small cooking axe',
img : 'img/knife11.jpg',
price : 24,
artist : 'ikel bangelo',
info : 'great for meat-chopping and dicing up other indgredients in large quanitities',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'knife12',
product_type: 'knife',
title : 'old handmade throwing blade',
img : 'img/knife12.jpg',
price : 20,
artist : 'lucy moon',
info : 'small throwing blade with wood-dye handle',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'pottery1',
product_type: 'pottery',
title : 'accesorizable vase',
img : 'img/pottery1.jpg',
price : 30,
artist : 'lucy moon',
info : 'collect amulets and hook them to this beautiful vase (two included)',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'pottery2',
product_type: 'pottery',
title : 'floral mug',
img : 'img/pottery2.jpg',
price : 5,
artist : 'ikel bangelo',
info : 'start your day with a cup of joe in this painted floral mug',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'pottery3',
product_type: 'pottery',
title : 'hearts mug',
img : 'img/pottery3.jpg',
price : 8,
artist : 'davito degal',
info : 'makes for a great valentines day gift',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'pottery4',
product_type: 'pottery',
title : 'colorful bowl',
img : 'img/pottery4.jpg',
price : 14,
artist : 'vince van dro',
info : 'impress company and serve your next snacks in this colorful bowl.',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'pottery5',
product_type: 'pottery',
title : 'night owl mug',
img : 'img/pottery5.jpg',
price : 13,
artist : 'lucy moon',
info : 'next time you need a cup of joe to burn the midnight oil consider this mug you old night owl you',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'pottery6',
product_type: 'pottery',
title : 'family tree mug',
img : 'img/pottery6.jpg',
price : 11,
artist : 'ikel bangelo',
info : 'apple tree design mug',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'pottery7',
product_type: 'pottery',
title : 'hand-painted mug',
img : 'img/pottery7.jpg',
price : 5,
artist : 'davito degal',
info : 'basic mug great gift for relatives or friends you dont really like that much.',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'pottery8',
product_type: 'pottery',
title : 'doggie bone bowl',
img : 'img/pottery8.jpg',
price : 15,
artist : 'vince van dro',
info : 'a beautiful bowl just for your best friend',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'pottery9',
product_type: 'pottery',
title : 'the meow mug',
img : 'img/pottery9.jpg',
price :14,
artist : 'lucy moon',
info : 'let your inner cat person out with the meow mug',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'pottery10',
product_type: 'pottery',
title : 'rainbow kitty bowl',
img : 'img/pottery10.jpg',
price : 9,
artist : 'ikel bangelo',
info : 'hand-made bowl for your kitten',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'pottery11',
product_type: 'pottery',
title : 'handmade mug with coaster',
img : 'img/pottery11.jpg',
price : 6,
artist : 'davito degal',
info : 'arts and crafts classic - coaster included',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'pottery12',
product_type: 'pottery',
title : 'turtle love',
img : 'img/pottery12.jpg',
price : 10,
artist : 'vince van dro',
info : 'love turtles ? great! now buy this mug.',
inCart : false,
count : 0,
total : 0,
id: null,
},
{ 
product_id : 'painting1',
product_type: 'painting',
title : '',
img : 'img/painting1.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'painting2',
product_type: 'painting',
title : '',
img : 'img/painting2.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'painting3',
product_type: 'painting',
title : '',
img : 'img/painting3.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'painting4',
product_type: 'painting',
title : '',
img : 'img/painting4.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'painting5',
product_type: 'painting',
title : '',
img : 'img/painting5.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'painting6',
product_type: 'painting',
title : '',
img : 'img/painting6.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'painting7',
product_type: 'painting',
title : '',
img : 'img/painting7.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'painting8',
product_type: 'painting',
title : '',
img : 'img/painting8.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'painting9',
product_type: 'painting',
title : '',
img : 'img/painting9.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'painting10',
product_type: 'painting',
title : '',
img : 'img/painting10.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'painting11',
product_type: 'painting',
title : '',
img : 'img/painting11.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'painting12',
product_type: 'painting',
title : '',
img : 'img/painting12.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'ww1',
product_type: 'ww',
title : '',
img : 'img/ww1.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'ww2',
product_type: 'ww',
title : '',
img : 'img/ww2.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'ww3',
product_type: 'ww',
title : '',
img : 'img/ww3.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'ww4',
product_type: 'ww',
title : '',
img : 'img/ww4.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'ww5',
product_type: 'ww',
title : '',
img : 'img/ww5.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'ww6',
product_type: 'ww',
title : '',
img : 'img/ww6.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'ww7',
product_type: 'ww',
title : '',
img : 'img/ww7.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'ww8',
product_type: 'ww',
title : '',
img : 'img/ww8.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'ww9',
product_type: 'ww',
title : '',
img : 'img/ww9.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'ww10',
product_type: 'ww',
title : '',
img : 'img/ww10.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'ww11',
product_type: 'ww',
title : '',
img : 'img/ww11.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'ww12',
product_type: 'ww',
title : '',
img : 'img/ww12.jpg',
price : '',
artist : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
}]
