export const navOpts = [
    [{
    name: "all-products"
    },{
    name: "pottery",
    },{
    name: "knives/swords",
    },{
    name: "paintings",
    },{
    name: "wood-work",
    }],
    [{
    name: "log-in",
    },{
    name: "sign-up",
    },{
    name: "log-out",
    },{
    name: "settings",
    },{
    name : "my-cart",
    }]
]

export const navHeadings = ["Products","Account"];

export const slides = [
    {img:"https://ffcp.s3.amazonaws.com/tfc/Resorts/palazzo/explore/arts_crafts/terrocotta_artisan/sizes/PM_artisans-9928.jpg",
    caption: "Welcome to Art Mart"},
    {img:"https://www.primeis.com/wp-content/uploads/2017/07/carpenter.jpg",
    caption: "A market and community of craftsmen, craftswomen, and seekers of unique hand-made crafts."}
]

export const signUpData = [
    [{
        label:'Username',
        type: 'text',
    },
    {
        label:'Email',
        type: 'email',
    }],
    [{
        label:'Password',
        type: 'password',
    },{
        label: 'Confirm Password',
        type: 'password'
    }],
    [{
        label:'Address',
        type: 'text',
    }],
    [{
        label:'City',
        type: 'text',
    },{
        label: 'State',
        type: 'select'
    },
    {
        label:'Zip',
        type: 'number',
    }],
    [{
        label:'Profile Picture',
        type: 'file',
    }],
    [{
        label: 'I have read and agree to follow the terms',
        type: 'checkbox',
    }]
]

export const logInData = [
    {
        label:'Username',
        type: 'text'
    },
    {
        label:'Email',
        type: 'email'
    },
    {
        label:'Password',
        type: 'password'
    }
]

export const columns = [
    [{
        name : "The goal behind the Art Mart is to provide an audience to those who like building things with their\
        hands all while presenting them with the opportunity to tell each item's story.",
        isLink: false
    }],
    [{
        name: "pottery",
        isLink: true
    },{
        name: "knives/swords",
        isLink: true
    },{
        name: "paintings",
        isLink: true
    },{
        name: "wood-work",
        isLink: true
    }],
    [{
        name: "about-us",
        isLink: true
    },{
        name: "terms",
        isLink: true
    },{
        name: "shipping-rates",
        isLink: true
    },{
        name: "help",
        isLink: true
    }],
    [{
        name: "Atlanta, GA 30305",
        isLink: false
    },{
        name: "artmart@gmail.com",
        isLink: false
    }],[{
        name: "2019 Copyright: Art Mart",
        isLink: false
    }]
]

export const headings = ["Art Mart","Products","Account","Contact"];

export const storeProducts = [
  { 
product_id : 'knife1',
product_type: 'knife',
title : '',
img : 'img/knife1.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'knife2',
product_type: 'knife',
title : '',
img : 'img/knife2.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'knife3',
product_type: 'knife',
title : '',
img : 'img/knife3.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'knife4',
product_type: 'knife',
title : '',
img : 'img/knife4.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'knife5',
product_type: 'knife',
title : '',
img : 'img/knife5.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'knife6',
product_type: 'knife',
title : '',
img : 'img/knife6.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'knife7',
product_type: 'knife',
title : '',
img : 'img/knife7.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'knife8',
product_type: 'knife',
title : '',
img : 'img/knife8.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'knife9',
product_type: 'knife',
title : '',
img : 'img/knife9.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'knife10',
product_type: 'knife',
title : '',
img : 'img/knife10.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'knife11',
product_type: 'knife',
title : '',
img : 'img/knife11.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'knife12',
product_type: 'knife',
title : '',
img : 'img/knife12.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'pottery1',
product_type: 'pottery',
title : '',
img : 'img/pottery1.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'pottery2',
product_type: 'pottery',
title : '',
img : 'img/pottery2.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'pottery3',
product_type: 'pottery',
title : '',
img : 'img/pottery3.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'pottery4',
product_type: 'pottery',
title : '',
img : 'img/pottery4.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'pottery5',
product_type: 'pottery',
title : '',
img : 'img/pottery5.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'pottery6',
product_type: 'pottery',
title : '',
img : 'img/pottery6.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'pottery7',
product_type: 'pottery',
title : '',
img : 'img/pottery7.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'pottery8',
product_type: 'pottery',
title : '',
img : 'img/pottery8.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'pottery9',
product_type: 'pottery',
title : '',
img : 'img/pottery9.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'pottery10',
product_type: 'pottery',
title : '',
img : 'img/pottery10.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'pottery11',
product_type: 'pottery',
title : '',
img : 'img/pottery11.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'pottery12',
product_type: 'pottery',
title : '',
img : 'img/pottery12.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'painting1',
product_type: 'painting',
title : '',
img : 'img/painting1.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'painting2',
product_type: 'painting',
title : '',
img : 'img/painting2.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'painting3',
product_type: 'painting',
title : '',
img : 'img/painting3.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'painting4',
product_type: 'painting',
title : '',
img : 'img/painting4.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'painting5',
product_type: 'painting',
title : '',
img : 'img/painting5.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'painting6',
product_type: 'painting',
title : '',
img : 'img/painting6.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'painting7',
product_type: 'painting',
title : '',
img : 'img/painting7.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'painting8',
product_type: 'painting',
title : '',
img : 'img/painting8.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'painting9',
product_type: 'painting',
title : '',
img : 'img/painting9.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'painting10',
product_type: 'painting',
title : '',
img : 'img/painting10.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'painting11',
product_type: 'painting',
title : '',
img : 'img/painting11.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'painting12',
product_type: 'painting',
title : '',
img : 'img/painting12.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'ww1',
product_type: 'ww',
title : '',
img : 'img/ww1.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'ww2',
product_type: 'ww',
title : '',
img : 'img/ww2.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'ww3',
product_type: 'ww',
title : '',
img : 'img/ww3.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'ww4',
product_type: 'ww',
title : '',
img : 'img/ww4.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'ww5',
product_type: 'ww',
title : '',
img : 'img/ww5.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'ww6',
product_type: 'ww',
title : '',
img : 'img/ww6.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'ww7',
product_type: 'ww',
title : '',
img : 'img/ww7.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'ww8',
product_type: 'ww',
title : '',
img : 'img/ww8.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'ww9',
product_type: 'ww',
title : '',
img : 'img/ww9.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'ww10',
product_type: 'ww',
title : '',
img : 'img/ww10.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'ww11',
product_type: 'ww',
title : '',
img : 'img/ww11.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
},
{ 
product_id : 'ww12',
product_type: 'ww',
title : '',
img : 'img/ww12.jpg',
price : '',
company : '',
info : '',
inCart : false,
count : 0,
total : 0,
id: '',
}]
